pipeline {
    agent any 

    environment {
        TOOL_DIR = "${WORKSPACE}/ci-cd-tools"
    }

    stages {
        stage('Build') { 
            steps {
                sh "make clean && make all"
            }
        }
/*
        stage('Static Code Analysis') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    sh "echo 'Running static code analysis...'"
                }
            }
        }
*/

        stage('Flash') { 
            steps {
                sh "make flash"
            }
        }
/*
        stage('Test-Debug') { 
            steps {
                sh "python3 ${TOOL_DIR}/base-hilt.py --dut-serial=$params.DUT_console --sim-serial=$params.SIM_console --tver=${BUILD_TAG}-Debug --jfile=test-results-debug.xml"
                junit 'test-results-debug.xml'
                sh "echo test-results-debug.xml"
            }
        }
*/
/*
        stage('Flash-Release') { 
            steps {
                sh "make clean && make all"
                sh "make flash"
            }
        }

        stage('Test-Release') { 
            steps {
                sh "python3 ${TOOL_DIR}/base-hilt.py --dut-serial=$params.DUT_console --sim-serial=$params.SIM_console --tver=${BUILD_TAG}-Release --jfile=test-results-release.xml"
                junit 'test-results-release.xml'
                sh "echo test-results-release.xml"
            }
        }
*/
    }

    post {
        success {
            sh "echo 'Build succeeded!'"
        }
        /*
        unsuccessful {
            script {
                emailext (
                    to: '${DEFAULT_RECIPIENTS}',
                    subject: "Unsuccessful build ${env.BUILD_ID}",
                    body: "Build ${env.BUILD_ID} has result ${currentBuild.currentResult}"
                )
            }
        }
        */
    }
}